export const CATEGORY_CREATE_REQUEST="CATEGORY_CREATE_REQUEST"
export const CATEGORY_CREATE_FAIL="CATEGORY_CREATE_FAIL"
export const CATEGORY_CREATE_SUCCESS="CATEGORY_CREATE_SUCCESS"

export const CATEGORY_GET_FAIL="CATEGORY_GET_FAIL"
export const CATEGORY_GET_SUCCESS="CATEGORY_GET_SUCCESS"
export const CATEGORY_GET_REQUEST="CATEGORY_GET_REQUEST"


export const CATEGORY_UPDATE_REQUEST="CATEGORY_UPDATE_REQUEST"
export const CATEGORY_DELETE_REQUEST="CATEGORY_DELETE_REQUEST"
export const CATEGORY_RESET_REQUEST="CATEGORY_RESET_REQUEST"