export const CATEGORY_CREATE_REQUEST="CATEGORY_CREATE_REQUEST"
export const CATEGORY_CREATE_FAIL="CATEGORY_CREATE_FAIL"
export const CATEGORY_CREATE_SUCCESS="CATEGORY_CREATE_SUCCESS"

export const CATEGORY_GET_FAIL="CATEGORY_GET_FAIL"
export const CATEGORY_GET_SUCCESS="CATEGORY_GET_SUCCESS"
export const CATEGORY_GET_REQUEST="CATEGORY_GET_REQUEST"


export const CATEGORY_DETAIL_REQUEST="CATEGORY_DETAIL_REQUEST"
export const CATEGORY_DETAIL_SUCCESS="CATEGORY_DETAIL_SUCCESS"
export const CATEGORY_DETAIL_FAIL="CATEGORY_DETAIL_SUCCESS"

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

export const CATEGORY_UPDATE_SUCCESS ='CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_REQUEST="CATEGORY_UPDATE_REQUEST"
export const CATEGORY_UPDATE_FAIL="CATEGORY_UPDATE_FAIL"
export const CATEGORY_UPDATE_RESET="CATEGORY_UPDATE_RESET"